"""S03 tracking and S05 versioned field research."""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "20260906_0022"
down_revision = "20260905_0021"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "field_material_profiles",
        sa.Column("material_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("sensitivity", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["field_materials.id"],
            name=op.f("fk_field_material_profiles_material_id_field_materials"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("material_id", name=op.f("pk_field_material_profiles")),
    )
    op.create_table(
        "field_text_versions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("material_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("parent_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column(
            "units",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_field_text_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["field_materials.id"],
            name=op.f("fk_field_text_versions_material_id_field_materials"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["field_text_versions.id"],
            name=op.f("fk_field_text_versions_parent_id_field_text_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["capability_runs.id"], name=op.f("fk_field_text_versions_run_id_capability_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_text_versions")),
        sa.UniqueConstraint("material_id", "version_no", name=op.f("uq_field_text_versions_material_id")),
    )
    op.create_index(
        op.f("ix_field_text_versions_material_id"), "field_text_versions", ["material_id"], unique=False
    )
    op.create_table(
        "field_segments",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("material_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("raw_version_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("clean_version_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "positions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clean_version_id"],
            ["field_text_versions.id"],
            name=op.f("fk_field_segments_clean_version_id_field_text_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["field_materials.id"],
            name=op.f("fk_field_segments_material_id_field_materials"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_version_id"],
            ["field_text_versions.id"],
            name=op.f("fk_field_segments_raw_version_id_field_text_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["capability_runs.id"], name=op.f("fk_field_segments_run_id_capability_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_segments")),
    )
    op.create_index(op.f("ix_field_segments_run_id"), "field_segments", ["run_id"], unique=False)
    op.create_index(op.f("ix_field_segments_material_id"), "field_segments", ["material_id"], unique=False)
    op.create_table(
        "field_annotations",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("segment_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_field_annotations_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"], ["field_segments.id"], name=op.f("fk_field_annotations_segment_id_field_segments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_annotations")),
        sa.UniqueConstraint("segment_id", "revision_no", name=op.f("uq_field_annotations_segment_id")),
    )
    op.create_index(
        op.f("ix_field_annotations_segment_id"), "field_annotations", ["segment_id"], unique=False
    )
    op.create_table(
        "field_excerpts",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("annotation_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["field_annotations.id"],
            name=op.f("fk_field_excerpts_annotation_id_field_annotations"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_field_excerpts_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_excerpts")),
        sa.UniqueConstraint("annotation_id", "kind", name=op.f("uq_field_excerpts_annotation_id")),
    )
    op.create_table(
        "tracking_items",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("config_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("identity", sa.String(length=64), nullable=False),
        sa.Column("material_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column(
            "snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "first_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["capability_configs.id"],
            name=op.f("fk_tracking_items_config_id_capability_configs"),
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["field_materials.id"],
            name=op.f("fk_tracking_items_material_id_field_materials"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_items")),
        sa.UniqueConstraint("config_id", "identity", name=op.f("uq_tracking_items_config_id")),
    )
    op.create_index(op.f("ix_tracking_items_config_id"), "tracking_items", ["config_id"], unique=False)
    op.create_table(
        "tracking_reviews",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("item_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_tracking_reviews_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["tracking_items.id"], name=op.f("fk_tracking_reviews_item_id_tracking_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_reviews")),
        sa.UniqueConstraint("item_id", "revision_no", name=op.f("uq_tracking_reviews_item_id")),
    )
    op.create_index(op.f("ix_tracking_reviews_item_id"), "tracking_reviews", ["item_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("tracking_reviews")
    op.drop_table("tracking_items")
    op.drop_table("field_excerpts")
    op.drop_table("field_annotations")
    op.drop_table("field_segments")
    op.drop_table("field_text_versions")
    op.drop_table("field_material_profiles")
