"""Immutable tracking observations and local schedule occurrences.

Revision ID: 20260907_0024
Revises: 20260907_0023
"""

from datetime import UTC

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "20260907_0024"
down_revision = "20260907_0023"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracking_observations",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("item_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("observation", sa.String(length=24), nullable=False),
        sa.Column(
            "snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"], ["tracking_items.id"], name=op.f("fk_tracking_observations_item_id_tracking_items")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["capability_runs.id"], name=op.f("fk_tracking_observations_run_id_capability_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_observations")),
        sa.UniqueConstraint("run_id", "item_id", name=op.f("uq_tracking_observations_run_id")),
    )
    op.create_index(
        op.f("ix_tracking_observations_item_id"), "tracking_observations", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_tracking_observations_run_id"), "tracking_observations", ["run_id"], unique=False
    )
    op.create_table(
        "tracking_schedules",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("config_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("local_time", sa.String(length=5), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("output_prompt", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["capability_configs.id"],
            name=op.f("fk_tracking_schedules_config_id_capability_configs"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_tracking_schedules_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_schedules")),
        sa.UniqueConstraint("config_id", name=op.f("uq_tracking_schedules_config_id")),
    )
    op.create_index(
        op.f("ix_tracking_schedules_next_run_at"), "tracking_schedules", ["next_run_at"], unique=False
    )
    op.create_table(
        "tracking_occurrences",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("schedule_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("occurrence_key", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "covered_slots",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.String(length=64), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "available_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("draft_revision_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "errors",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["draft_revision_id"],
            ["capability_run_revisions.id"],
            name=op.f("fk_tracking_occurrences_draft_revision_id_capability_run_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["capability_runs.id"], name=op.f("fk_tracking_occurrences_run_id_capability_runs")
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["tracking_schedules.id"],
            name=op.f("fk_tracking_occurrences_schedule_id_tracking_schedules"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_occurrences")),
        sa.UniqueConstraint("draft_revision_id", name=op.f("uq_tracking_occurrences_draft_revision_id")),
        sa.UniqueConstraint("run_id", name=op.f("uq_tracking_occurrences_run_id")),
        sa.UniqueConstraint(
            "schedule_id", "occurrence_key", name=op.f("uq_tracking_occurrences_schedule_id")
        ),
    )
    op.create_index(
        op.f("ix_tracking_occurrences_schedule_id"), "tracking_occurrences", ["schedule_id"], unique=False
    )
    op.create_index(op.f("ix_tracking_occurrences_status"), "tracking_occurrences", ["status"], unique=False)
    op.create_table(
        "tracking_deliveries",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("occurrence_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("research_case_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "observation_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["occurrence_id"],
            ["tracking_occurrences.id"],
            name=op.f("fk_tracking_deliveries_occurrence_id_tracking_occurrences"),
        ),
        sa.ForeignKeyConstraint(
            ["research_case_id"],
            ["research_cases.id"],
            name=op.f("fk_tracking_deliveries_research_case_id_research_cases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_deliveries")),
        sa.UniqueConstraint("occurrence_id", name=op.f("uq_tracking_deliveries_occurrence_id")),
    )
    op.create_index(
        op.f("ix_tracking_deliveries_research_case_id"),
        "tracking_deliveries",
        ["research_case_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    op.add_column("tracking_reviews", sa.Column("observation_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        "fk_tracking_reviews_observation",
        "tracking_reviews",
        "tracking_observations",
        ["observation_id"],
        ["id"],
    )
    op.create_index("ix_tracking_reviews_observation_id", "tracking_reviews", ["observation_id"])
    # Historical reviews lacked immutable snapshot identity. Retain them unattached, never infer adoption.
    bind = op.get_bind()
    runs = bind.execute(sa.text("SELECT id, output FROM capability_runs WHERE output IS NOT NULL"))
    for run_id, output in runs:
        import hashlib
        import json
        from datetime import datetime

        output = json.loads(output) if isinstance(output, str) else output
        if not isinstance(output, dict) or output.get("type") != "policy_tracking_workflow":
            continue
        for observation in output.get("observations", []):
            snapshot = observation.get("snapshot") or {}
            item_id = observation.get("item_id")
            if (
                not item_id
                or not bind.execute(
                    sa.text("SELECT id FROM tracking_items WHERE id=:id"), {"id": item_id}
                ).scalar()
            ):
                continue
            observed = snapshot.get("observed_at")
            try:
                observed = datetime.fromisoformat(observed) if observed else datetime.now(UTC)
            except ValueError:
                observed = datetime.now(UTC)
            table = sa.table(
                "tracking_observations",
                sa.column("run_id"),
                sa.column("item_id"),
                sa.column("fingerprint"),
                sa.column("observation"),
                sa.column("snapshot", sa.JSON()),
                sa.column("observed_at"),
            )
            bind.execute(
                table.insert().values(
                    run_id=run_id,
                    item_id=item_id,
                    fingerprint=snapshot.get("fingerprint")
                    or hashlib.sha256(json.dumps(snapshot, sort_keys=True).encode()).hexdigest(),
                    observation=observation.get("observation", "unknown"),
                    snapshot=snapshot,
                    observed_at=observed,
                )
            )


def downgrade():
    op.drop_index("ix_tracking_reviews_observation_id", table_name="tracking_reviews")
    op.drop_constraint("fk_tracking_reviews_observation", "tracking_reviews", type_="foreignkey")
    op.drop_column("tracking_reviews", "observation_id")
    op.drop_table("tracking_deliveries")
    op.drop_table("tracking_occurrences")
    op.drop_table("tracking_schedules")
    op.drop_table("tracking_observations")
