"""Invitation accounts and version-bound field material grants.

Revision ID: 20260907_0023
Revises: 20260906_0022
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "20260907_0023"
down_revision = "20260906_0022"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reader_login_attempts",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reader_login_attempts")),
    )
    op.create_index(
        op.f("ix_reader_login_attempts_created_at"), "reader_login_attempts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_reader_login_attempts_identity_hash"),
        "reader_login_attempts",
        ["identity_hash"],
        unique=False,
    )
    op.create_table(
        "reader_accounts",
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_reader_accounts_user_id_users")),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_reader_accounts")),
    )
    op.create_table(
        "reader_invitations",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("invited_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("token_sha256", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["invited_by"], ["users.id"], name=op.f("fk_reader_invitations_invited_by_users")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_reader_invitations_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reader_invitations")),
        sa.UniqueConstraint("token_sha256", name=op.f("uq_reader_invitations_token_sha256")),
    )
    op.create_index(op.f("ix_reader_invitations_user_id"), "reader_invitations", ["user_id"], unique=False)
    op.create_table(
        "reader_sessions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("token_sha256", sa.String(length=64), nullable=False),
        sa.Column("csrf_sha256", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_reader_sessions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reader_sessions")),
        sa.UniqueConstraint("token_sha256", name=op.f("uq_reader_sessions_token_sha256")),
    )
    op.create_index(op.f("ix_reader_sessions_expires_at"), "reader_sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_reader_sessions_user_id"), "reader_sessions", ["user_id"], unique=False)
    op.create_table(
        "field_asset_versions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("material_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["field_materials.id"],
            name=op.f("fk_field_asset_versions_material_id_field_materials"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_asset_versions")),
        sa.UniqueConstraint("material_id", "version_no", name=op.f("uq_field_asset_versions_material_id")),
    )
    op.create_index(
        op.f("ix_field_asset_versions_material_id"), "field_asset_versions", ["material_id"], unique=False
    )
    op.create_table(
        "field_comments",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("material_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("author_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("parent_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("hidden", sa.Boolean(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_field_comments_author_id_users")),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["field_materials.id"],
            name=op.f("fk_field_comments_material_id_field_materials"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["field_comments.id"], name=op.f("fk_field_comments_parent_id_field_comments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_comments")),
    )
    op.create_index(op.f("ix_field_comments_material_id"), "field_comments", ["material_id"], unique=False)
    op.create_table(
        "field_community_events",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("material_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("actor_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_field_community_events_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["field_materials.id"],
            name=op.f("fk_field_community_events_material_id_field_materials"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_community_events")),
    )
    op.create_index(
        op.f("ix_field_community_events_material_id"), "field_community_events", ["material_id"], unique=False
    )
    op.create_table(
        "field_project_grants",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("asset_version_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("research_case_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("requested_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column(
            "permissions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("ai_provider", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status in ('pending','approved','rejected','revoked')",
            name=op.f("ck_field_project_grants_status"),
        ),
        sa.ForeignKeyConstraint(
            ["asset_version_id"],
            ["field_asset_versions.id"],
            name=op.f("fk_field_project_grants_asset_version_id_field_asset_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["users.id"], name=op.f("fk_field_project_grants_decided_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_field_project_grants_requested_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["research_case_id"],
            ["research_cases.id"],
            name=op.f("fk_field_project_grants_research_case_id_research_cases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_project_grants")),
        sa.UniqueConstraint(
            "asset_version_id", "research_case_id", name=op.f("uq_field_project_grants_asset_version_id")
        ),
    )
    op.create_index(
        op.f("ix_field_project_grants_asset_version_id"),
        "field_project_grants",
        ["asset_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_project_grants_research_case_id"),
        "field_project_grants",
        ["research_case_id"],
        unique=False,
    )
    op.create_index(op.f("ix_field_project_grants_status"), "field_project_grants", ["status"], unique=False)
    op.create_table(
        "field_publications",
        sa.Column("material_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("asset_version_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("public_title", sa.String(length=240), nullable=False),
        sa.Column("introduction", sa.Text(), nullable=False),
        sa.Column("excerpts", sa.Text(), nullable=False),
        sa.Column("image_key", sa.String(length=200), nullable=True),
        sa.Column("image_sha256", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status in ('draft','published','withdrawn')", name=op.f("ck_field_publications_status")
        ),
        sa.ForeignKeyConstraint(
            ["asset_version_id"],
            ["field_asset_versions.id"],
            name=op.f("fk_field_publications_asset_version_id_field_asset_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["field_materials.id"],
            name=op.f("fk_field_publications_material_id_field_materials"),
        ),
        sa.PrimaryKeyConstraint("material_id", name=op.f("pk_field_publications")),
    )
    op.create_index(op.f("ix_field_publications_status"), "field_publications", ["status"], unique=False)
    op.create_table(
        "field_project_links",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("asset_version_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("research_case_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("grant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("added_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["added_by"], ["users.id"], name=op.f("fk_field_project_links_added_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["asset_version_id"],
            ["field_asset_versions.id"],
            name=op.f("fk_field_project_links_asset_version_id_field_asset_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["field_project_grants.id"],
            name=op.f("fk_field_project_links_grant_id_field_project_grants"),
        ),
        sa.ForeignKeyConstraint(
            ["research_case_id"],
            ["research_cases.id"],
            name=op.f("fk_field_project_links_research_case_id_research_cases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_project_links")),
        sa.UniqueConstraint(
            "asset_version_id", "research_case_id", name=op.f("uq_field_project_links_asset_version_id")
        ),
    )
    op.create_index(
        op.f("ix_field_project_links_asset_version_id"),
        "field_project_links",
        ["asset_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_project_links_research_case_id"),
        "field_project_links",
        ["research_case_id"],
        unique=False,
    )
    op.create_table(
        "field_run_bindings",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("asset_version_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("grant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_version_id"],
            ["field_asset_versions.id"],
            name=op.f("fk_field_run_bindings_asset_version_id_field_asset_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["field_project_grants.id"],
            name=op.f("fk_field_run_bindings_grant_id_field_project_grants"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["capability_runs.id"], name=op.f("fk_field_run_bindings_run_id_capability_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_run_bindings")),
        sa.UniqueConstraint("run_id", "asset_version_id", name=op.f("uq_field_run_bindings_run_id")),
    )
    op.create_index(
        op.f("ix_field_run_bindings_asset_version_id"),
        "field_run_bindings",
        ["asset_version_id"],
        unique=False,
    )
    op.create_index(op.f("ix_field_run_bindings_grant_id"), "field_run_bindings", ["grant_id"], unique=False)
    op.create_index(op.f("ix_field_run_bindings_run_id"), "field_run_bindings", ["run_id"], unique=False)
    op.create_table(
        "field_run_rights_reviews",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("grant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["field_project_grants.id"],
            name=op.f("fk_field_run_rights_reviews_grant_id_field_project_grants"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_field_run_rights_reviews_reviewed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["capability_runs.id"],
            name=op.f("fk_field_run_rights_reviews_run_id_capability_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_run_rights_reviews")),
        sa.UniqueConstraint("run_id", "grant_id", name=op.f("uq_field_run_rights_reviews_run_id")),
    )
    op.create_index(
        op.f("ix_field_run_rights_reviews_grant_id"), "field_run_rights_reviews", ["grant_id"], unique=False
    )
    op.create_index(
        op.f("ix_field_run_rights_reviews_run_id"), "field_run_rights_reviews", ["run_id"], unique=False
    )

    # Preserve explicit historical project uploads with concrete asset/grant/link records.
    # No files are read or modified, and no public descriptions are created.
    bind = op.get_bind()
    metadata = sa.MetaData()
    materials = sa.Table("field_materials", metadata, autoload_with=bind)
    assets = sa.Table("field_asset_versions", metadata, autoload_with=bind)
    grants = sa.Table("field_project_grants", metadata, autoload_with=bind)
    links = sa.Table("field_project_links", metadata, autoload_with=bind)
    for material in bind.execute(sa.select(materials)).mappings():
        asset_id = bind.execute(
            assets.insert()
            .values(
                material_id=material["id"],
                version_no=1,
                sha256=material["sha256"],
                storage_key=material["storage_key"],
                created_at=material["created_at"],
            )
            .returning(assets.c.id)
        ).scalar_one()
        if material["research_case_id"] and material["authorization_confirmed"]:
            grant_id = bind.execute(
                grants.insert()
                .values(
                    asset_version_id=asset_id,
                    research_case_id=material["research_case_id"],
                    requested_by=material["owner_id"],
                    decided_by=material["owner_id"],
                    purpose="保留迁移前上传者对原项目的明确使用授权",
                    permissions=["read", "ai", "cite", "download"],
                    ai_provider="legacy_configured_runtime",
                    status="approved",
                    created_at=material["created_at"],
                    updated_at=material["updated_at"],
                )
                .returning(grants.c.id)
            ).scalar_one()
            bind.execute(
                links.insert().values(
                    asset_version_id=asset_id,
                    research_case_id=material["research_case_id"],
                    grant_id=grant_id,
                    added_by=material["owner_id"],
                    active=True,
                    created_at=material["created_at"],
                )
            )


def downgrade():
    op.drop_table("field_run_rights_reviews")
    op.drop_table("field_run_bindings")
    op.drop_table("field_project_links")
    op.drop_table("field_publications")
    op.drop_table("field_project_grants")
    op.drop_table("field_community_events")
    op.drop_table("field_comments")
    op.drop_table("field_asset_versions")
    op.drop_table("reader_sessions")
    op.drop_table("reader_invitations")
    op.drop_table("reader_accounts")
    op.drop_table("reader_login_attempts")
